### ISSUE TITLE
Parts of Widget not visible - Tree Profile Widget

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/planet-widgets#23] opened 2021-02-04 17:23 UTC
When opening the Tree Profile Widget HTML Code in my Browser
it cuts off the left and upper part of the Widget (see screenshot).

It doesn't matter how big the Browser Window or if Fullscreen or not.
It doesn't matter which theme, etc.
![mozilla_widget_tree_profile_space](https://user-images.githubusercontent.com/18365824/106929974-513f2900-6715-11eb-8620-fe7592524bd3.PNG)

Widget code used:
```
<script defer src="https://widgets.plant-for-the-planet.org/build/tree-profile.js"></script>
<tree-profile user="prf_h6smcMDN23Qet1CP7BEplM60" theme="light" primarycolor="#000000" circlebgcolor="#000000" community="false" locale="de"></tree-profile>
```

This problem does not exist for the Tree Map Widget.

My Browsers that I tried it in all showed it the same cut off way  (64-Bit)
Firefox Version 88.0.4324.104
Chrome Version 88.0.4324.104
Edge Version 88.0.705.56
Internet Explorer: won't load the Widget at all cause it is Internet Explorer

**Comment by sagararyal** [comment] 2021-02-04 22:09
@delightedMatt this is not a bug.

You need to declare HTML and add the tags either inside <head> or <body> tags

```
<!DOCTYPE html>
<html>
<body>
	<script defer src="https://widgets.plant-for-the-planet.org/build/tree-profile.js"></script>
	<tree-profile user="prf_h6smcMDN23Qet1CP7BEplM60" theme="light" primarycolor="#000000" circlebgcolor="#000000" community="false" locale="de"></tree-profile>
</body>
</html>
```

Please close the issue if this solves.

**Closed** 2021-02-05 13:24 UTC
Labels: bug

**Comment by delightedMatt** [comment] 2021-02-05 13:39
Cough. Thank you. Cough. That was dumb of me. Cough.
